spring:
  application:
    name: photo-service
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    pool:
      enabled: true
      initial-size: 30
      max-acquire-time: 5s
      max-create-connection-time: 5s
      max-idle-time: 60m
      max-life-time: 60m
      max-size: 50
  flyway:
    url: ${FLYWAY_URL}
    baseline-on-migrate: true
    enabled: true
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

app:
  gateway:
    endpoint: https://gateway.mafoo.kr
  user:
    endpoint: http://user-service

cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${NCP_BUCKET}
      presigned-url-expiration: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  zipkin:
    tracing:
      endpoint: http://zipkin/api/v2/spans

slack:
  webhook:
    token: ${SLACK_TOKEN}
    channel:
      error: ${SLACK_ERROR_CHANNEL}
      qr: ${SLACK_QR_ERROR_CHANNEL}

ffmpeg:
  path: /usr/bin/ffmpeg

recap:
  max-size: 5
  path:
    tmp: /usr/bin/recap/tmp/
    src: /usr/bin/recap/src/

lambda:
  endpoint: ${LAMBDA_URL}
