package kr.mafoo.photo.domain.enums;

public enum NotificationType {
    REGULAR,
    EVENT,

    NEW_MEMBER,
    NEW_MEMBER_INVITED,

    SHARED_MEMBER_INVITATION_CREATED,
    SHARED_MEMBER_INVITATION_REJECTED,
    SHARED_MEMBER_INVITATION_ACCEPTED,

    SHARED_MEMBER_ADDED_TO_ALBUM,
    SHARED_MEMBER_REMOVED_FROM_ALBUM,

    RECAP_CREATED
}
