spring:
  application:
    name: user-service
  flyway:
    url: ${FLYWAY_URL}
    baseline-on-migrate: true
    enabled: true
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    pool:
      enabled: true
      initial-size: 30
      max-acquire-time: 5s
      max-create-connection-time: 5s
      max-idle-time: 60m
      max-life-time: 60m
      max-size: 50
logging:
  level:
    org.springframework.data.r2dbc: DEBUG

app:
  gateway:
    endpoint: https://gateway.mafoo.kr
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URL}
    apple:
      client-id: ${APPLE_CLIENT_ID}
  jwt:
    verify-key: ${JWT_VERIFY_KEY}
    expiration:
      access-token: 2592000 # 30 days
      refresh-token: 2592000 # 30 days

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  zipkin:
    tracing:
      endpoint: http://zipkin/api/v2/spans

slack:
  webhook:
    token: ${SLACK_TOKEN}
    channel:
      error: ${SLACK_ERROR_CHANNEL}
      member: ${SLACK_MEMBER_CHANNEL}

cloud:
  firebase: ${FIREBASE_SECRET}
